#1注册中心：用于注册服务 访问地址http://localhost:8761
server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: localhost
#    perferIpAddress: true
  #2在默认情况下erureka server也是一个eureka client ,必须要指定一个 server
  client:
  #3通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false   #是否将自身注册到别的eureka上
    fetchRegistry: false     #是否合并别的eureka上数据，如果为true，启动时报警.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    responseCacheUpdateIntervalMs: 5000
    eviction-interval-timer-in-ms: 3000 #启用主动失效，并且每次主动失效检测间隔为3s